version: '3.8'
services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
    - 8081:80
    volumes:
    - ./web/html:/usr/share/nginx/html
    - /var/run/docker.sock:/var/run/docker.sock